### PR TITLE
fix(openai): track client attributes for v1 SDK of OpenAI

### LINKED ISSUE #479: 🚀 Feature: Add more properties to Span Attributes for OpenAI instrumentation
### Which component is this feature for?

OpenAI Instrumentation

### 🔖 Feature description

The OpenAI instrumentation is great, but is missing some span attributes compared with the httpx instrumentor that would be useful to capture.  I'd like to know what the client attributes were for the OpenAI client like the host and the deployment name. Those are in `SpanAttributes.HTTP_METHOD` and `SpanAttributes.HTTP_URL`.

### 🎤 Why is this feature needed ?

I'm using different OpenAI backends (Azure OpenAI) and want to capture the deployment name, the host name and other information that is in the client.

### ✌️ How do you aim to achieve this?

Add some additional span attributes to the trace that capture the properties of the open ai client object.

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by tonybaloney**
Adds base URL to the openAI v1+ SDK and the API version for Azure OpenAI

Fixes #479 

Before:

```default
Trace 12391879d7721f635e8c81ece142a59a
└── [08:53:43.832568] openai.embeddings, span 8a0632a8f425452a
    ├── Kind : CLIENT
    ├── Attributes : 
    │   ├── llm.request.type : embedding
    │   ├── llm.vendor : OpenAI
    │   ├── llm.request.model : embedding
    │   ├── llm.headers : None
    │   ├── llm.prompts.0.content : Ground control to Major Tom
    │   ├── llm.response.model : ada
    │   ├── llm.usage.total_tokens : 5
    │   └── llm.usage.prompt_tokens : 5
    └── Resources : 
        ├── telemetry.sdk.language : python
        ├── telemetry.sdk.name : opentelemetry
        ├── telemetry.sdk.version : 1.23.0
        └── service.name : unknown_service
```

After

```
Trace 2a237cbb28690e6a7841486a82211b14
└── [08:58:27.483496] openai.embeddings, span 2e300bb34bda19b4
    ├── Kind : CLIENT
    ├── Attributes : 
    │   ├── llm.request.type : embedding
    │   ├── llm.vendor : OpenAI
    │   ├── llm.request.model : embedding
    │   ├── llm.headers : None
    │   ├── llm.prompts.0.content : Ground control to Major Tom
    │   ├── openai.api_base : https://<redacted>.openai.azure.com/openai/
    │   ├── openai.api_version : 2023-07-01-preview
    │   ├── llm.response.model : ada
    │   ├── llm.usage.total_tokens : 5
    │   └── llm.usage.prompt_tokens : 5
    └── Resources : 
        ├── telemetry.sdk.language : python
        ├── telemetry.sdk.name : opentelemetry
        ├── telemetry.sdk.version : 1.23.0
        └── service.name : unknown_service
```

### CODE REVIEW

**Comment by nirga** [comment]
Thanks @tonybaloney! Can you add a test for that?

**Comment by tonybaloney** [comment]
> Thanks @tonybaloney! Can you add a test for that?

Sure. Where are the existing test cases?

**Comment by nirga** [comment]
> > Thanks @tonybaloney! Can you add a test for that?
> 
> Sure. Where are the existing test cases?

https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-openai/tests

**Review by nirga — APPROVED** [review]
Nice work @tonybaloney, thank you so much!

**Pull request merged**
