### PR TITLE
fix(sdk): `aentity_class` was missing a positional argument

### PR DESCRIPTION
**Pull request by Carlososuna11**
- [ ] I have added tests that cover my changes.
- [ ] If adding a new instrumentation or changing an existing one, I've added screenshots from some observability platform showing the change.
- [ ] PR name follows conventional commits format: `feat(instrumentation): ...` or `fix(instrumentation): ...`.
- [ ] (If applicable) I have updated the documentation accordingly.

### CODE REVIEW

**Review by nirga — COMMENTED** [review]
Nice! Thanks for spotting and fixing this! Mind adding a test for this so it won't happen again?

**Comment by nirga** [comment]
@Carlososuna11 do you mind signing the CLA? I won't be able to merge your PR otherwise

**Comment by nirga** [comment]
friendly ping @Carlososuna11

**Comment by Carlososuna11** [comment]
Done! Sorry

**Review by nirga — APPROVED** [review]

**Pull request merged**
