### PR TITLE
Added logging for content filter

### PR DESCRIPTION
**Pull request by dtee1**
- [ ] I have added tests that cover my changes.
- [ ] If adding a new instrumentation or changing an existing one, I've added screenshots from some observability platform showing the change.
- [ ] PR name follows conventional commits format: `feat(instrumentation): ...` or `fix(instrumentation): ...`.
- [ ] (If applicable) I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nirga** [comment]
Thanks @dtee1 but I think we already wrap everything with a try-catch and log an exception (see the `@dont_throw` annotation)

**Comment by dtee1** [comment]
> Thanks @dtee1 but I think we already wrap everything with a try-catch and log an exception (see the `@dont_throw` annotation)

Ok sounds good. I can take that out. Would you rather I just log the warning in an else?

**Comment by nirga** [comment]
> > Thanks @dtee1 but I think we already wrap everything with a try-catch and log an exception (see the `@dont_throw` annotation)
> 
> 
> 
> Ok sounds good. I can take that out. Would you rather I just log the warning in an else?

We also log there 😀

**Comment by dtee1** [comment]
> > > Thanks @dtee1 but I think we already wrap everything with a try-catch and log an exception (see the `@dont_throw` annotation)
> > 
> > 
> > Ok sounds good. I can take that out. Would you rather I just log the warning in an else?
> 
> We also log there 😀

Ok, how is the fix #855 supposed to be implemented? Maybe I missed something

**Comment by nirga** [comment]
@dtee1 so when calling azure it may filter the response returned from the model if it contains harmful text, see https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=warning%2Cpython-new

We should add attributes to the span according to those returned from azure in this case.

**Comment by nirga** [comment]
Superseded by #1539

**Pull request closed without merging**
