### PR TITLE
feat(weaviate): implement weaviate instrumentation

### PR DESCRIPTION
**Pull request by paolorechia**
Work in progress. Keeping it open as draft for more visibility :)

### CODE REVIEW

**Comment by paolorechia** [comment]
@nirga This is taking a bit longer than I expected :)

Note that I haven't yet tested it with vectors, I think there's some additional work involved there. I need to figure out how to vectorize what goes inside weaviate.

For now, this is just the basic instrumentation around CRUD / query.

**Comment by paolorechia** [comment]
Example run of sample app:

```
Traceloop exporting traces to https://api.traceloop.com authenticating with bearer token

/home/paolo/dev/openllmetry/packages/traceloop-sdk/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/dependencies.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import (
/home/paolo/dev/openllmetry/packages/traceloop-sdk/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py:2868: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/paolo/dev/openllmetry/packages/traceloop-sdk/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py:2868: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/paolo/dev/openllmetry/packages/traceloop-sdk/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py:2348: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(parent)
/home/paolo/dev/openllmetry/packages/traceloop-sdk/.venv/lib/python3.10/site-packages/weaviate/warnings.py:121: DeprecationWarning: Dep005: You are using weaviate-client version 3.26.2. The latest version is 4.4.2.
            Please consider upgrading to the latest version. See https://weaviate.io/developers/weaviate/client-libraries/python for details.
  warnings.warn(
Created schema
Retrieved schema:  {'class': 'Article', 'description': 'An Article class to store a text', 'invertedIndexConfig': {'bm25': {'b': 0.75, 'k1': 1.2}, 'cleanupIntervalSeconds': 60, 'stopwords': {'additions': None, 'preset': 'en', 'removals': None}}, 'multiTenancyConfig': {'enabled': False}, 'properties': [{'dataType': ['text'], 'description': 'The name of the author', 'indexFilterable': True, 'indexSearchable': True, 'name': 'author', 'tokenization': 'whitespace'}, {'dataType': ['text'], 'description': 'The text content', 'indexFilterable': True, 'indexSearchable': True, 'name': 'text', 'tokenization': 'word'}], 'replicationConfig': {'factor': 1}, 'shardingConfig': {'virtualPerPhysical': 128, 'desiredCount': 1, 'actualCount': 1, 'desiredVirtualCount': 128, 'actualVirtualCount': 128, 'key': '_id', 'strategy': 'hash', 'function': 'murmur3'}, 'vectorIndexConfig': {'skip': False, 'cleanupIntervalSeconds': 300, 'maxConnections': 64, 'efConstruction': 128, 'ef': -1, 'dynamicEfMin': 100, 'dynamicEfMax': 500, 'dynamicEfFactor': 8, 'vectorCacheMaxObjects': 1000000000000, 'flatSearchCutoff': 40000, 'distance': 'cosine', 'pq': {'enabled': False, 'bitCompression': False, 'segments': 0, 'centroids': 256, 'trainingLimit': 100000, 'encoder': {'type': 'kmeans', 'distribution': 'log-normal'}}}, 'vectorIndexType': 'hnsw', 'vectorizer': 'none'}
Created object of UUID:  f70533c7-3a7d-48c4-86a3-fe52d6bfa768
Retrieved obj:  {'class': 'Article', 'creationTimeUnix': 1707341304837, 'id': 'f70533c7-3a7d-48c4-86a3-fe52d6bfa768', 'lastUpdateTimeUnix': 1707341304837, 'properties': {'author': 'Robert', 'text': 'Once upon a time, someone wrote a book...'}, 'vectorWeights': None}
Query result: {'data': {'Get': {'Article': [{'author': 'Maverick'}, {'author': 'Wilson'}, {'author': 'Robert'}, {'author': 'Ludwig'}, {'author': 'Johnson'}, {'author': 'Robert'}]}}}
Aggregate result: {'data': {'Aggregate': {'Article': [{'meta': {'count': 6}}]}}}
Raw result:  {'data': {'Get': {'Article': [{'author': 'Maverick', 'text': 'Never again, M. will write a book...'}, {'author': 'Wilson', 'text': 'Lost in the island, W. did not write anything...'}]}}}
Deleted schema...
```

Screenshots:

image
image
image
image
image
image

**Comment by nirga** [comment]
@paolorechia LMK when can I review it. I think the main thing we might be missing here is just setting this up with VCR.py

**Comment by paolorechia** [comment]
@nirga If you're OK with it, as soon as this is rebased and the tests are converted to use vcrpy. I would still need to look into how to retrieve vector embeddings with weaviate, but we could do it in a follow-up PR.

**Comment by nirga** [comment]
SG @paolorechia! Thank you!

**Comment by paolorechia** [comment]
@nirga I might need your input here. I've updated everything but I seem to be missing something in the setup, I keep getting this error:

```
 ___________ ERROR collecting tests/test_weaviate_instrumentation.py ____________
ImportError while importing test module '/home/runner/work/openllmetry/openllmetry/packages/opentelemetry-instrumentation-weaviate/tests/test_weaviate_instrumentation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_weaviate_instrumentation.py:5: in <module>
    from traceloop.sdk.decorators import task
E   ModuleNotFoundError: No module named 'traceloop'
```

If I inspect for instance, Pinecone instrumentation package, it doesn't define traceloop-sdk as a dependency. Yet it works fine. For weaviate instrumentation, this is not the case.

If I do add a circular dependency, e.g., add traceloop-sdk as a dependency of weaviate instrumentation (only for testing), then the tests work fine. That is, doing this:

```
[tool.poetry.group.test.dependencies]
#  other deps defined here... 
traceloop-sdk = {path="../traceloop-sdk", develop=true}
```

I've done this in the last commit and it works, but it seems like I'm missing something here.

**Comment by paolorechia** [comment]
@nirga  I am also blocked by this issue: https://github.com/kevin1024/vcrpy/issues/533
Trying to find a solution to it.

**Comment by paolorechia** [comment]
@nirga I've made some progress in understanding the issue here. There are few different issues at hand here:

1. Weaviate seems to do a heartbeat check. This does not always fail a test, as it runs in a background thread. If the test takes longer, it's more likely to fail.
2. Turns out that the batch request from weaviate v3 client uses a ThreadPool, which makes the underlying requests not recorded by vcrpy in the first place. I configured pytest to skip the `create_batch` test for now, as I don't have a solution to this.
3. I removed all unnecessary calls in the test after a recording is provided. This means, for instance, a `test_query_raw` only really calls `query_raw`. This seems to remove the flakiness in tests. It's probably related to the heartbeat check in the background, since the tests are short they don't live long enough to trigger the check (my hypothesis). This does add the drawback that recording a new cassette is not so easy, as the tests won't work out of the box since it presumes state.

**Review by nirga — APPROVED** [review]

**Pull request merged**
