### PR TITLE
Fix issues and made some changes

### PR DESCRIPTION
**Pull request by mohizzzol**
- [x] I have added tests that cover my changes.
- [ ] If adding a new instrumentation or changing an existing one, I've added screenshots from some observability platform showing the change.
- [x] PR name follows conventional commits format: `feat(instrumentation): ...` or `fix(instrumentation): ...`.
- [x] (If applicable) I have updated the documentation accordingly.

### CODE REVIEW

**Review by nirga — COMMENTED** [review]
Hey @mohizzzol can you explain the purpose of this PR, or alternatively split into multiple ones, each fixing one issue?

**Comment by mohizzzol** [comment]
in this i did some good updates that's needed

**Comment by mohizzzol** [comment]
The purpose of this PR is to consolidate various fixes and improvements identified in our recent work. However, to enhance clarity and streamline the review process, I can split it into multiple PRs, with each one dedicated to fixing a specific issue. This will make it easier to review and track changes individually.

**Comment by nirga** [comment]
@mohizzzol before you do that - can you briefly explain what are you fixing?

**Comment by mohizzzol** [comment]
In this PR, we addressed several issues related to the OpenTelemetry Aleph Alpha instrumentation:

Improved Instrumentation: We fixed inconsistencies in how telemetry data was being collected, ensuring more accurate tracking of metrics.
Bug Fixes: We resolved specific bugs that caused incorrect data reporting, which enhances the reliability of our monitoring tools.
Code Optimization: We optimized the code for better performance and maintainability, making it easier for future contributions.
If needed, we can split this PR into multiple ones, each focusing on a specific issue for clarity.

**Comment by nirga** [comment]
Please do, explaining what but specifically you're addressing. I don't understand what "inconsistencies" were fixed here :/

**Comment by mohizzzol** [comment]
The purpose of this PR is to address various inconsistencies in the OpenTelemetry Aleph Alpha instrumentation. Specifically, we focused on:

Documentation Updates: We clarified the usage of certain functions and fixed typos to enhance readability and understanding.
Code Consistency: We standardized naming conventions across the codebase to ensure uniformity and prevent confusion.
Bug Fixes: We identified and resolved specific issues that were causing incorrect behavior in the instrumentation, improving overall functionality.
If you need a more granular breakdown, I can split the PR into multiple ones, each focusing on a single issue or fix.

**Comment by mohizzzol** [comment]
Yes, the pull request is still in progress. We're currently addressing the feedback regarding the inconsistencies and refining the documentation. Once we finalize these adjustments, we will seek an approving review to proceed with the merge. Thank you for your patience!

**Comment by mohizzzol** [comment]
Are you merging it?

**Pull request closed without merging**
