### PR TITLE
feat: Updated semantic conventions based on otel community

### PR DESCRIPTION
**Pull request by gyliu513**
Adopting https://github.com/open-telemetry/semantic-conventions/pull/825

- [ ] I have added tests that cover my changes.
- [ ] If adding a new instrumentation or changing an existing one, I've added screenshots from some observability platform showing the change.
- [ ] PR name follows conventional commits format: `feat(instrumentation): ...` or `fix(instrumentation): ...`.
- [ ] (If applicable) I have updated the documentation accordingly.

Fixed https://github.com/traceloop/openllmetry/issues/880

@nirga ^^

### CODE REVIEW

**Comment by nirga** [comment]
Looks good! @gyliu513 
You'll probably have some work updating the tests as well since many of them (🤦 ) aren't referencing the semconvs directly

**Comment by nirga** [comment]
@gyliu513 oh and one more thing - because of `poetry` limitation, the semantic convention package is always pulled from `pypi`. So I'll need to manually publish a version so that the build here will pass. Let me know when I can do that

**Comment by gyliu513** [comment]
@nirga ready to go, can you help review and switch to the "official" semantic convention constants? Thanks!

**Comment by nirga** [comment]
Done @gyliu513

**Review by nirga — APPROVED** [review]

**Pull request merged**
