### PR TITLE
fix(langchain): BedrockChat model name should be model_id

### LINKED ISSUE #762: 🐛 Bug Report: Error getting model name when using langchain BedrockChat
### Which component is this bug for?

Langchain Instrumentation

### 📜 Description

When using latest `opentelemetry-instrumentation-langchain@0.15.11` with the `traceloop-sdk@0.15.11` in a langchain app that works with AWS Bedrock models, `custom_chat_wrapper` throws error when getting model name in `_handle_request`.

### 👟 Reproduction steps

```python
from langchain_community.chat_models import BedrockChat

llm = BedrockChat(
    region_name="us-east-1",
    model_id="anthropic.claude-3-sonnet-20240229-v1:0",
    endpoint_url="https://bedrock-runtime.us-east-1.amazonaws.com",
    name="my_bedrock_model",
    model_kwargs={
        "max_tokens": 1024,
        "temperature": 0.5,
    },
)

chain = prompt | llm
chain.invoke("Tell a joke")
```

### 👍 Expected behavior

The Bedrock chat model should be instrumented without any errors.

### 👎 Actual Behavior with Screenshots

It throws an error:

```
 /Users/xxx/Library/Caches/pypoetry/virtualenvs/xxx/lib/python3.11/site-packages/opentelemetry/instrumentation/langchain/custom_chat_wrapper.py:43 in
 _handle_request

   40
   41 def _handle_request(span, args, kwargs, instance):
   42 │   print(instance)
 ❱ 43 │   model = instance.model if hasattr(instance, "model") else instance.model_name
   44 │   span.set_attribute(SpanAttributes.LLM_REQUEST_TYPE, LLMRequestTypeValues.CHAT.value)
   45 │   span.set_attribute(SpanAttributes.LLM_REQUEST_MODEL, model)
   46 │   span.set_attribute(SpanAttributes.LLM_RESPONSE_MODEL, model)

AttributeError: 'BedrockChat' object has no attribute 'model_name'
```

### 🤖 Python Version

3.11.8

### 📃 Provide any additional context for the Bug.

I've printed the `instance` object:

```
client=<botocore.client.BedrockRuntime object at 0x11db649d0> region_name='us-east-1'
model_id='anthropic.claude-3-haiku-20240307-v1:0' model_kwargs={'max_tokens': 1024, 'temperature': 0.5}
endpoint_url='https://bedrock-runtime.us-east-1.amazonaws.com' name='my_bedrock_model'
```

So far as I know:

* `ChatAnthropic` uses `model` or `model_name` (https://github.com/langchain-ai/langchain/blob/039b7a472d3628f2b484bf2814f9e7e677adf738/libs/partners/anthropic/langchain_anthropic/chat_models.py#L231)
* `ChatOpenAI` uses `model_name` or `model` (https://github.com/langchain-ai/langchain/blob/039b7a472d3628f2b484bf2814f9e7e677adf738/libs/partners/openai/langchain_openai/chat_models/base.py#L277)
* `BedrockChat` (`BedrockBase`) uses `model_id` (https://github.com/langchain-ai/langchain/blob/039b7a472d3628f2b484bf2814f9e7e677adf738/libs/community/langchain_community/llms/bedrock.py#L322)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by evisong**
Fixes #762

- [x] I have added tests that cover my changes.
- [x] If adding a new instrumentation or changing an existing one, I've added screenshots from some observability platform showing the change.
- [x] PR name follows conventional commits format: `feat(instrumentation): ...` or `fix(instrumentation): ...`.
- [ ] (If applicable) I have updated the documentation accordingly.

### CODE REVIEW

**Comment by evisong** [comment]
I have some difficulties make the UT passes due to AWS credentials. 

In my local environment, there are `~/.aws` config files, the `test_bedrock` passed without `os.environ["AWS_*"]`. As soon as I remove those config files, `test_bedrock` failed, no matter what env vars are.

I still need some time to find the solution. Any help will be appreciated.

**Comment by evisong** [comment]
The UT finally passed. Sorry for so many failed trials due to my limited experience of `vcrpy`.

**Review by nirga — APPROVED** [review]

**Comment by nirga** [comment]
Nice @evisong!

**Comment by evisong** [comment]
According to https://github.com/traceloop/openllmetry/issues/762#issuecomment-2046708935 I was trying to add `try-except`, but I hesitated about its scope, so I give the model a fallback name "unknown", what do you think?

**Review by nirga — APPROVED** [review]
Nice work @evisong!

**Pull request merged**
