### PR TITLE
fix(llamaindex): support both new and legacy llama_index versions

### PR DESCRIPTION
**Pull request by alex-feel**
This commit fixes issues introduced in 5e5bc88443ae80cc38a4aef3bf1e5744be355f9e by enhancing the dynamic loading mechanism for `llama-index` modules to ensure compatibility across both `llama-index-core` and `llama-index-legacy`. Modifications include updates across various instrumentor files to correctly reference modules based on the installed `llama-index` version. These changes address errors encountered during initialization and ensure seamless operation with both versions of `llama-index`.

- Dynamically set `_instruments` in `__init__.py` based on package version.
- Adjust `MODULE_NAME` in instrumentor files to support new and legacy structures.

### CODE REVIEW

**Comment by alex-feel** [comment]
I apologize for the oversight in the previous commit. It missed some critical aspects of handling the `llama-index` package versions. I've now made the necessary adjustments to ensure compatibility with both the core and legacy versions. Thank you for your patience and understanding as we improve our project together.

**Comment by alex-feel** [comment]
I apologize for the oversight in the previous commit. It missed some critical aspects of handling the `llama-index` package versions. I've now made the necessary adjustments to ensure compatibility with both the core and legacy versions. Thank you for your patience and understanding.

**Comment by alex-feel** [comment]
It looks like everything is ok now.

**Comment by nirga** [comment]
Thanks again @alex-feel! I wonder if it's too much to ask of you to write a small test for this, just to make sure it works on the latest version of `llamaindex`? You can copy-paste the test structure from other instrumentations like OpenAI.

**Comment by alex-feel** [comment]
Thank you for your feedback and the suggestion to add a test. I would be more than happy to take on this task under normal circumstances. However, I'm currently tied up with an urgent project that demands my full attention and cannot divert my focus at this moment.

Regarding the issue addressed in https://github.com/traceloop/openllmetry/pull/423, I want to add that the current fix specifically targets and resolves the problem mentioned. I have conducted manual testing on `llama_index.core` to ensure the fix is effective and have verified that the imports are correct for `llama_index.legacy`.

**Comment by nirga** [comment]
No worries @alex-feel, I'll add them. Tested it on `llama-index` v0.9.48 and it didn't work so I'll work on fixing that as well.

**Comment by alex-feel** [comment]
I've updated this branch with an additional commit that reinstates the original changes which my fix addresses. To recap, the original update was designed to enhance the import logic by dynamically supporting both the new (`llama_index.core.llms`) and legacy (`llama_index.legacy.llms.custom`) versions of the `llama_index` package. This approach utilizes conditional imports and adjusts `MODULE_NAME` dynamically, ensuring compatibility across different versions of the package. This improvement significantly enhances the flexibility and maintainability of our codebase in accommodating the evolving `llama_index` library.

**Review by nirga — APPROVED** [review]

**Pull request merged**
